$title: Workflow
$order: -1
description: See how we get things done

ng_controller: WorkflowController

components:
- component: nav
  logo:
    url: /static/images/logo.png
    alt: Logo
  links:
    - name: About
      url: /about
    - name: Projects
      url: /projects
    - name: Workflow
      url: /workflow
    - name: Contact
      url: /contact
- component: footer